server:
  port: 38085
spring:
  application:
    name: statistics
  datasource:
    dynamic:
      primary: qianlima #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        qianlima:
          username: root
          password: qianlima
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.18.30.34:3306/qianlima?characterEncoding=UTF-8
        modmonitor:
          username: statistics
          password: KF7lhEE3AIwM
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://121.40.46.25:3309/modmonitor?useUnicode=true&characterEncoding=utf8
        octopus:
          username: statistics
          password: KF7lhEE3AIwM
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://121.40.203.166:3309/spiderbridge?useUnicode=true&characterEncoding=utf8
        spiderplatform:
          username: root
          password: qianlima
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.18.30.34:3306/spiderplatform?useUnicode=true&characterEncoding=gbk
        rawdatas:
          username: root
          password: qianlima
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.18.30.34:3306/spiderplatform?useUnicode=true&characterEncoding=utf8
  data:
    mongodb:
      uri: mongodb://172.18.30.34:27017/qlmdb
xxl:
  job:
    admin:
      addresses: http://xxl-dev.intra.qianlima.com/xxl-job-admin-1.8.2
    executor:
      appname: ${spring.application.name}
      ip:
      port: 9991
      logretentiondays: 1
      logpath:
    accessToken:

#是否开启 swagger-ui
swagger:
  enabled: true