server:
  port: 9002
  tomcat:
    basedir: /root/domesticOutfit/temp
spring:
  application:
    name: bishe
  datasource:
    dynamic:
      primary: bishe #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        bishe:
          username: root
          password: AAFB2ID2Hq2P
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.24.21.49:3306/bishe?characterEncoding=UTF-8
      mvc:
        static-path-pattern: /**
      resources:
        static-locations: file:/root/domesticOutfit/images

  data:
    mongodb:
      uri: mongodb://172.24.21.49:27017/bishe

swagger:
  enabled: true

file:
  path:
    absolute: /root/domesticOutfit/images
    relative: /
