server:
  port: 9001
  tomcat:
    basedir: /Users/gaomac/domesticOutfit/temp
spring:
  application:
    name: bishe
  datasource:
    dynamic:
      primary: bishe #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        bishe:
          username: root
          password: gyx521.369
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/bishe?characterEncoding=UTF-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:/Users/gaomac/domesticOutfit/images

  data:
    mongodb:
      uri: mongodb://47.94.201.4:27017/bishe


#是否开启 swagger-ui
swagger:
  enabled: true



file:
  path:
    absolute: /Users/gaomac/domesticOutfit/images
    relative: /